const products={
 ai:{label:'TMS AI • AI OPERATING SYSTEM',title:'TMS AI',text:'Une plateforme d’intelligence et d’exécution contrôlée pour transformer un objectif en opération vérifiable.',features:['Assistant • Missions • Agents • Automation','Revenue OS • CRM • Communication & Commerce','Execution • Verification • Recovery • Governance','Autonomie graduée : Assisted → Autopilot']},
 toolkit:{label:'TMS TOOLKIT • TECHNICAL OPERATIONS',title:'TMS TOOLKIT',text:'Une plateforme technique dédiée au diagnostic, à l’engineering et aux opérations contrôlées sur appareils.',features:['Device Detector • Driver Manager • ADB/Fastboot','Firmware Manager • Verification Engine','Flashing Center • Post-Flash Diagnostic','Recovery • Flash Report & Audit']},
 digital:{label:'TMS DIGITAL • BUSINESS OPERATIONS',title:'TMS DIGITAL',text:'Un environnement digital orienté gestion, clients, ventes, services et opérations.',features:['ERP • Clients • Produits • Services','Ventes et suivi commercial','Gestion opérationnelle structurée','Architecture connectable à TMS AI']},
 workstation:{label:'TMS WORKSTATION • PRODUCTION CONTROL',title:'TMS WORKSTATION',text:'Le cockpit central de production et de contrôle pour les projets TMS.',features:['Windows SOURCE_OF_TRUTH','Build • Release • Documentation • Archive','Diagnostic mobile et recovery via Android/Termux','Contrôle des versions et validations']}
};
const modal=document.querySelector('#productModal');
function openProduct(key){const p=products[key];if(!p||!modal)return;document.querySelector('#modalEyebrow').textContent=p.label;document.querySelector('#modalTitle').textContent=p.title;document.querySelector('#modalText').textContent=p.text;document.querySelector('#modalFeatures').innerHTML=p.features.map(x=>`<div>✓ ${x}</div>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');}
function closeProduct(){if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');}
document.querySelectorAll('.preview-btn').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.product)));
document.querySelector('#closeProduct')?.addEventListener('click',closeProduct);document.querySelector('#modalCatalogClose')?.addEventListener('click',closeProduct);modal?.addEventListener('click',e=>{if(e.target===modal)closeProduct();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeProduct();});